### ISSUE TITLE
[Suggestion] Add {folder} variable.

### ISSUE THREAD

**Issue by Strencher** [satoqz/vscode-discord#131]
It would be cool to have a variable replacement called `{folder}` that will be replaced with the active files' folder. I have my projects in subfolders so it just shows `Documents` all the time as workspace. lol

I already locally edited the extension and added the variable but i can't seem to get it to run. (let me know if you know how, i would make a PR then.) This is the code i got so far, should be working fine but as i said, couldn't get it to test.
```ts
// util.ts
export const resolveCurrentFolder = (file: string): string =>
	file.split(/(\\|\/)/).slice(-3).shift();

// parser.ts
this.presence.state = workspace.name
	? this.config.get<string>("workspaceText")
		.replace(/{folder}/g, resolveCurrentFolder(window.activeTextEditor.document.fileName))
		.replace(/{workspace}/g, workspace.name)
	: "No workspace";
```

**Comment by satoqz** [comment]
good request, i'd like to implement it myself because i have some ideas on how to restructure the util file. If you were wondering how to debug the extension locally, you have to first build it with typescript and then go to the vscode debug section and select debug extension (while doing so make sure to disable the extension installed from the marketplace)

**Comment by Strencher** [comment]
Alright, thanks for the help. I really appreciate your work.
