### ISSUE TITLE
The extension don't show up the riche precense on gnu+linux

### ISSUE THREAD

**Issue by ViniDalvino** [Satoqz/vscode-discord#15]
I use Ubuntu 20.04.1 LTS
Here is what the developper tool dev console say:  https://pastebin.com/DsMNfD3K

**Comment by ViniDalvino** [comment]
I tried reloading the rpc but it still edidnt showed up

**Comment by Satoqz** [comment]
The extension works on linux, I've personally used it on multiple distributions. It looks like you've installed vscode (maybe also discord) using the snap store as i can tell from your logs. Applications installed using snap run in a sandbox environment which makes IPC impossible because the vscode process cannot "connect" to the discord process. What you'll need to do is to install vscode and discord without a sandboxed environment, on ubuntu either through apt or by downloading the .deb directly from the web. (I personally try to minimize the usage of snap at all costs)
