### ISSUE TITLE
Multiple VSCode instances

### ISSUE THREAD

**Issue by LoaderB0T** [Satoqz/vscode-discord#27]
Hi there,

is this extension supposed to work with multiple instances of vscode?

I have two pen windows but the extension does only seem to care about the one I opened first. When I switch Windows, I would expect the extension to show the information about the new window, instead, it says "idling" after a few moments.

**Comment by Satoqz** [comment]
Hello,

sadly  i know of no way to intercommunicate between vscode processes in order to achieve the effect that you are describing.

Basically, when an application is connecting to your discord client to show rich presence information, it "secures a spot" in discord and is the only application whose information will be shown. While an application is already connected, others will also be able to connect to discord without an error, but only the presence of the application that has connected first will be shown. As soon as that application is closed, the existing connections to other applications that have been established later on will be used.

So if you open vscode instance #1 and it connects, only the rich presence of that instance will be shown. When you open vscode instance #2, it will successfully connect but only be shown as soon as connection #1 is closed. So to resolve this issue, the vscode instances would have to intercommunicate and dynamically open/close their connection to discord based e.g. which window you are focusing. So there's probably no easy way to fix this, though it may be possible. I might do some testing when i have the time.

**Comment by LoaderB0T** [comment]
Maybe the solution is not to communicate between the instances, but to check if the window is unfocused and stop the connection instead of showing idle?

**Comment by Satoqz** [comment]
I could add an option to disconnect if the window has been unfocused for a specific amount of time and immediately reconnect when it is focused again. This might actually be a decent solution, will get to work on it eventually.

**Comment by Satoqz** [comment]
This should now be implemented ([commit](https://github.com/Satoqz/vscode-discord/commit/6022c6e252cee2b68d4ffc47e95e3f67848fdc64)). Please review the changelog and tell me if you're satisfied with the changes :smile:

**Comment by LoaderB0T** [comment]
Works like a charm! Thanks, that was really fast! :)
